spring:
  datasource:
    url: jdbc:postgresql://payments-db:5432/payment
    username: postgres
    password: payment123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    properties:
      security.protocol: PLAINTEXT
    admin:
      auto-create: true
    consumer:
      group-id: payments-service-group-2
      # auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "org.*, java.util, java.lang"
    #producer:
    #  key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #  value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  level:
    org.example: DEBUG
    org.springframework.kafka: DEBUG 