spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/eshop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092